version: "3.8"
services:
  postgres:
    image: postgres:11
    container_name: postgres
    expose:
      - "5432"
    networks:
      - web-postgres
    environment:
      POSTGRES_PASSWORD: root
      POSTGRES_USER: postgres
      POSTGRES_DB: autobusiness
  web:
    image: auto-business
    #image: ubuntu
    #stdin_open: true
    #tty: true
    #entrypoint: /bin/bash
    build:
      context: .
    container_name: web-app
    expose:
      - "5432"
    ports:
      - "9090:9090"
    networks:
      - web-postgres
    depends_on:
      - postgres
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://172.18.0.2:5432/autobusiness
    #  - SPRING_DATASOURCE_USERNAME=postgres
    #  - SPRING_DATASOURCE_PASSWORD=root
    #  - SPRING_JPA_HIBERNATE_DDL_AUTO=none
networks:
  web-postgres: