logging:
  level:
    org:
      hibernate:
        type: debug

server:
  port: 9090
  error:
    include-message: always

spring:
  data:
    mongodb:
      host: "localhost"
      port: 27017
      database: "auto-business"
  main:
    allow-bean-definition-overriding: true #TODO: docs
  application:
    name: autobusiness
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/autobusiness
    username: postgres
    password: root
    name: autobusiness
  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

feign:
  encoder:
    charset-from-content-type: true

jwt:
  token:
    secret: jwtsecret
    expired: 360000000

currency:
  client:
    url: https://www.cbr-xml-daily.ru/daily_json.js

sorting:
  default-field: brand
  default-direction: ASC

test:
  containers:
    postgres:
      name: autobusiness
      version: postgres:11.1
      port: 55050 #${random.int[50000, 60000]}
      username: postgres
      password: root
      driver-class-name: org.postgresql.Driver