logging:
  level:
    org:
      hibernate:
        type: debug

server:
  port: 9090
  error:
    include-message: always

spring:
  application:
    name: autobusiness
  jpa:
    hibernate:
      ddl-auto: none
    generate-ddl: false
  datasource:
    url: jdbc:postgresql://localhost:5432/autobusiness
    username: postgres
    password: root
  jackson:
    serialization:
      fail-on-empty-beans: false

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false

feign:
  encoder:
    charset-from-content-type: true

jwt:
  token:
    secret: jwtsecret
    expired: 360000000

currency:
  client:
    url: https://www.cbr-xml-daily.ru/daily_json.js

sorting:
  default-field: brand
  default-direction: ASC